### ISSUE TITLE
YourBittorrent returns duplicates

### ISSUE THREAD

**Issue by hdcTenBasePid** [LightDestory/qBittorrent-Search-Plugins#5] opened 2022-01-28 15:48 UTC
**Results are being returned repeated 9 times for each found torrent.**
This occurs about 90% of time and I can't figure out why.
i.e. Search for 'seeds 1968' (and some others) work fine but the rest overpopulate.
e.g. Some searches return many thousands of unneeded duplicates.

A small example of the problem: 
![2022-01-28 015825_qBt_search](https://user-images.githubusercontent.com/16771012/151569666-68689550-b4fd-4884-a391-90fff0f641e6.png)

**Environment: Windows 10H 21H2**
- qBittorrent: 4.2.1 / 4.3.9 / 4.4.0
- Python: 3.9.2
- YourBittorrent: 1.1

**Here is a possible solution by changing 3 items and adding 4 lines:**
- declare new variable: **found[]**, before _HTMLParser_ definition,
- change signature of of _feed_ method to include it: **def feed(self, html, found)**,
- change _prettyPrinter(data)_ line to:
```
if data not in found:
	found.append(data.copy())
```
  in _search_ method:

- change _parser.feed(html)_ to: **parser.feed(html, self.found)**,
- add following code after the for loop:
```

self.found.sort(key=lambda x: int(x.get('seeds')))  # Sorted per guidelines
for data in self.found:
	prettyPrinter(data)
```

You can see the logic - collect new torrents to a list, sort list and prettyPrint list.

Hope my idea has merit.
Thanks for your great work.

**Comment by LightDestory** [comment] 2022-01-31 11:07
Thanks for your contribution. I will check the cause of the issue and try to fix it.

Your solution is nice but it over-fit the engine role. The engine must only parse the webpages not alter their content.

The engines doesn't now produce any line of data, so if the items get duplicated there is a issue on the parser or webpage.

I will look into them.

**Comment by LightDestory** [comment] 2022-01-31 17:53
It should be fixed with e7f3079e5c1e5da328da99b630e959d90e8319e0

Feel free to open this issue again if the problem is still affecting you.

**Comment by Obegg** [comment] 2022-02-22 08:11
Hey, seems like the issue has not been solved.
I'm on ```# VERSION: 1.2``` and search results seem duplicated.

**Comment by LightDestory** [comment] 2022-02-22 08:34
> Hey, seems like the issue has not been solved. I'm on `# VERSION: 1.2` and search results seem duplicated.

Try 1.3 and let me know.

YorBittorrent pagination has been removed, the searh will fetch only the first 50 torrent (as per website default) so you need to input a more specific query.

**Comment by Obegg** [comment] 2022-02-22 08:38
1.3 seems to fix the issue.
Thank you!

**Closed** 2022-02-22 08:41 UTC
Labels: bug
